#!/bin/bash

SCRIPT=`basename $0`
DROOT=$HOME/.dotfiles
IROOT=$DROOT/.init

if [ -f $IROOT/download ]; then
    source $IROOT/download
fi

if [ -f $IROOT/symlink ]; then
    source $IROOT/symlink
fi

if [ -f $IROOT/configure ]; then
    source $IROOT/configure
fi
