#!/bin/bash

DROOT=$HOME/.dotfiles

# ------------------
# Symlinking
# ------------------

echo "+Symlinking configuration files to home..."

SKIP=( .git .gitignore .init README.md)

shopt -s dotglob # allows (temporarily) wildcard to match hidden files

for absfile in $DROOT/*
do
    file=`basename $absfile`

    symlink=true
    for pattern in ${SKIP[@]}
    do
        if [ $pattern = $file ]
        then
            symlink=false
        fi
    done

    if [ $symlink = true ]
    then
        # TODO: handle directories well
        echo "Sym linking $DROOT/$file to $HOME/$file"
        ln -sf $DROOT/$file $HOME/$file
    fi
done

shopt -u dotglob # we restore the globbing behaviour back to normal

echo ""
