#!/bin/sh 
BRANCH=${1:-master}
for dir in `find . -maxdepth 1 -mindepth 1 -type d`
do
    (cd $dir &&
        if [ -d .git ]; then
            echo "${Green}Found a git repository at ${Yellow}$dir${Green}, attempting to pull from ${BRANCH}${Reset_Style}"
            CURRENT_BRANCH=`git branch | grep \* | cut -d ' ' -f2`
            git checkout -q ${BRANCH} 2> /dev/null && git pull 
            git checkout -q $CURRENT_BRANCH
        fi;
    )
done
